version: '3'
services:
  mysql:
    restart: always
    privileged: true
    image: mysql:5.7
    container_name: uu9db
    volumes:
      - ./db/:/var/lib/mysql
      - ./conf/:/etc/mysql/conf.d
      - ./logs/:/logs
      - ./init/:/docker-entrypoint-initdb.d/
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: "1234qwer"
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
    ports:
      - 3306:3306
    network_mode: "bridge"
 
